### ISSUE TITLE
Enhancement: Add option to make a specific audio the default track and a specific subtitle track a forced track

### ISSUE THREAD

**Issue by jcdr428** [justdan96/tsMuxer#126]
Cf. https://forum.doom9.org/showthread.php?p=1895226#post1895226 :
`Actually, you can do it yourself in any HEX editor. Open MovieObject.bdmv, find 42 82 00 00 00 00 00 00 00 00 00 0A and insert next digits BEFORE 42 82 00 00 00 00 00 00 00 00 00 0A:

51 C0 00 01 80 01 C0 01 00 00 00 00
where:
1 - number of default audio track
1 - number of default subtitle track
C - all elements in selected PGS are shown. If you need to show only elements that marked with Forced="True" flag - you need to use 8 instead of C

Additionally it is needed to replace 03 80 00 00 05 for 03 80 00 00 06

But i agree that it would be more convinient to select needed default and forced tracks from gui or cli.`

**Comment by xavery** [comment]
I have an implementation (no GUI yet) somewhat ready in my [`default-and-forced-track`](https://github.com/xavery/tsMuxer/tree/default-and-forced-tracks) branch. Setting the audio track works okay. However, the only BD player (of sorts) that I can test with is VLC, which seems to interpret the command differently with regards to the subtitle track : when the byte is set to `C`, the subtitle track is properly selected and plays normally. However, setting it to `8` causes the player to deselect it altogether, as if there was no command for setting the subtitle track.
@jcdr428 Hopefully you can shed some light on this?

**Comment by jcdr428** [comment]
@tymoxa I hope you can help xavery on this.

**Comment by tymoxa** [comment]
@xavery when the subtitle byte set to C it's basicaly like setting Disp_s_flag to true, that is showing ALL subtitles elements in that paricular PG stream. when we change that byte to 8 - we change Disp_s_flag to false (that's why subtitle track become deselected in VLC). In combination with "number of default subtitle track" it gives us ability to show only Forced="True" elements in that particular PG stream. i think it is better to add two commands to Additional parameters for PG and SRT tracks:  default-all (to byte C) and default-forced (to byte 8)

**Comment by xavery** [comment]
@tymoxa Thanks a ton.
