### ISSUE TITLE
Problem at tsMuxerGUI with Non-ASCII char in path to .mpls in Windows 10 64bit

### ISSUE THREAD

**Issue by abakum** [justdan96/tsMuxer#172]
![image](https://user-images.githubusercontent.com/18271863/73627448-cd63e400-465d-11ea-8ad2-475869f727d3.png)

**Comment by abakum** [comment]
Not only cyrillic but Non-ASCII too
![image](https://user-images.githubusercontent.com/18271863/73632545-11121a00-466d-11ea-8fb8-9657f5137cf6.png)

**Comment by abakum** [comment]
Not only tsMuxerGUI but tsMuxer too:
D:\YandexDisk\PortableApps\tsMuxeR>tsMuxeR.exe "d:\AV\2020\20200111 ДР Аллы\film\BD\BDMV\PLAYLIST\00001.mpls"
tsMuxeR version git-39bb829. github.com/justdan96/tsMuxer
Track ID:    4113
Stream type: H.264
Stream ID:   V_MPEG4/ISO/AVC
Stream info: Profile: High@4.2  Resolution: 1920:1080p  Frame rate: 50
Stream lang:

Track ID:    4352
Stream type: LPCM
Stream ID:   A_LPCM
Stream info: Bitrate: 1536Kbps  Sample Rate: 48KHz  Channels: 2  Bits per sample: 16bit
Stream lang: rus

Track ID:    4608
Stream type: PGS
Stream ID:   S_HDMV/PGS
Stream info: Presentation Graphic Stream #0 Resolution: 1920:1080 Frame rate: 50
Stream lang: rus

File #00000 name=d:\AV\2020\20200111 ДР Аллы\film\BD\BDMV\STREAM\00001.m2ts
Duration: 00:12:42.159
start-time: 189000000
Marks: 00:00:00.000 00:00:22.559 00:00:39.820 00:01:32.140 00:04:20.620
Marks: 00:05:24.439 00:07:34.519 00:08:33.539 00:10:06.659 00:11:22.980


D:\YandexDisk\PortableApps\tsMuxeR>tsMuxeR.exe "c:\AV\ä\BD\BDMV\PLAYLIST\00001.mpls"
tsMuxeR version git-39bb829. github.com/justdan96/tsMuxer

There is not even an error output!
D:\YandexDisk\PortableApps\tsMuxeR>tsMuxeR12.exe "c:\AV\ä\BD\BDMV\PLAYLIST\00001.mpls"
Network Optix tsMuxeR.  Version 2.6.12. www.networkoptix.com

There is not even an error output!

**Comment by abakum** [comment]
D:\YandexDisk\PortableApps\tsMuxeR>tsMuxeR12.exe c:\AV\ä\BD\BDMV\STREAM\00001.m2ts
Network Optix tsMuxeR.  Version 2.6.12. www.networkoptix.com
Error: Can't open stream c:\AV\a\BD\BDMV\STREAM\00001.m2ts

D:\YandexDisk\PortableApps\tsMuxeR>tsMuxeR.exe c:\AV\ä\BD\BDMV\STREAM\00001.m2ts
tsMuxeR version git-39bb829. github.com/justdan96/tsMuxer
Error: Can't open stream c:\AV\a\BD\BDMV\STREAM\00001.m2ts

**Comment by jcdr428** [comment]
@abakum 
- What font do you have in (regedit) HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Console\TrueTypeFont key "00", is it "Consolas" ?
- In the cmd console, when you type "chcp" command, which code type does it return ?

**Comment by abakum** [comment]
1) Consolas
2) 866

**Comment by abakum** [comment]
c:\AV\ä\BD\BDMV\PLAYLIST>chcp
Текущая кодовая страница: 866

c:\AV\ä\BD\BDMV\PLAYLIST>d:\YandexDisk\PortableApps\tsMuxeR\tsmuxer.exe 00001.mpls
tsMuxeR version git-39bb829. github.com/justdan96/tsMuxer
Error: Can't open stream 00001.m2ts

c:\AV\ä\BD\BDMV\PLAYLIST>d:\YandexDisk\PortableApps\tsMuxeR\tsmuxer12.exe 00001.mpls
Network Optix tsMuxeR.  Version 2.6.12. www.networkoptix.com
Error: Can't open stream 00001.m2ts

c:\AV\ä\BD\BDMV\PLAYLIST>chcp 1251
Текущая кодовая страница: 1251

c:\AV\ä\BD\BDMV\PLAYLIST>d:\YandexDisk\PortableApps\tsMuxeR\tsmuxer.exe 00001.mpls
tsMuxeR version git-39bb829. github.com/justdan96/tsMuxer
Error: Can't open stream 00001.m2ts

c:\AV\ä\BD\BDMV\PLAYLIST>chcp 65001
Active code page: 65001

c:\AV\ä\BD\BDMV\PLAYLIST>d:\YandexDisk\PortableApps\tsMuxeR\tsmuxer.exe 00001.mpls
tsMuxeR version git-39bb829. github.com/justdan96/tsMuxer
Error: Can't open stream 00001.m2ts

c:\AV\ä\BD\BDMV\PLAYLIST>cd \

c:\>d:\YandexDisk\PortableApps\tsMuxeR\tsmuxer.exe c:\AV\ä\BD\BDMV\PLAYLIST\00001.mpls
tsMuxeR version git-39bb829. github.com/justdan96/tsMuxer

**Comment by abakum** [comment]
c:>d:\YandexDisk\PortableApps\tsMuxeR\tsmuxer.exe c:\AV\ä\BD\BDMV\PLAYLIST\00001.mpls
tsMuxeR version git-39bb829. github.com/justdan96/tsMuxer

There is not even an error output!

**Comment by justdan96** [comment]
I'll see if I can reproduce this one, if it is literally just non-ASCII characters in the file paths should be relatively straightforward to reproduce.

**Comment by jcdr428** [comment]
@justdan96 I can't reproduce with my Windows 10 : path such as ...\ä\BD\BDMV\PLAYLIST\00001.mpls works perfectly. Same story as the locale, hence the reason to suspect the font or code type -but the problem seems to be elsewhere.

**Comment by justdan96** [comment]
Odd - maybe try running procmon to figure out what is going on.

**Comment by xavery** [comment]
Unfortunately, what you're trying to do will never work with the current code on Windows due to how tsMuxeR currently handles paths. The console application is not built with `UNICODE`, which means that the paths to be opened are converted via the `A`-variant of WinAPI functions, which means that converting any character outside the code page supported by the "active code page" is not possible.
@abakum 's active code page is probably set to Windows-1251, seeing how he's probably running a Russian/East-European version of Windows. @justdan96 and @jcdr428 are running West-European versions of Windows and their active code pages are most probably Windows-1252.
The character `ä` is not supported by Win1251, but is supported by Win1252. I bet that the program is going to fail for you guys if you try putting a Cyrillic character in the path used by tsMuxeR, for example `Я`.
The only way to fix this is to ensure that the underlying file is opened in tsMuxeR by calling the "wide" variants of WinAPI functions, i.e. the ones that end with `W`. I don't remember the details well enough to tell for sure, but this should *hopefully* be limited to libmediation only.
PS. Shameless self plug - I [really like](https://www.youtube.com/watch?v=h5Q3yMIK5XQ) the topic of character encodings. ;-)

**Comment by jcdr428** [comment]
@xavery 🥇 great lecture !
