### ISSUE TITLE
MUXOPT option --label for .iso does not work with non ASCII characters

### ISSUE THREAD

**Issue by abakum** [justdan96/tsMuxer#185]
If iso.meta with
MUXOPT --blu-ray --label="20200111 ДР Аллы" --vbr --vbv-len=500
... 
encoded in windows-1251 result after
tsMuxeR.exe iso.meta "20200111 ДР Аллы.iso"
like:
![2020-02-07_13-37-29](https://user-images.githubusercontent.com/18271863/74037937-62553d00-49d0-11ea-85f4-57b1f2e7dbca.png)
If iso.meta encoded in UTF-8 result like:
![2020-02-07_13-49-15](https://user-images.githubusercontent.com/18271863/74038025-86188300-49d0-11ea-9c0a-b52eea0d22d6.png)
It would be great to have it like after imgBurn:
![2020-02-07_13-56-39](https://user-images.githubusercontent.com/18271863/74038173-cc6de200-49d0-11ea-958a-c58a385158b5.png)

**Comment by justdan96** [comment]
@xavery is this still the case?

**Comment by abakum** [comment]
This problem was before switching to Unicode

**Comment by xavery** [comment]
@justdan96 Unfortunately yes, this is completely unrelated to the changes I've made recently regarding Unicode handling around the application. However, implementing this properly wouldn't even be possible without them.
Anyhow, the issue is with how the code in `iso_writer.cpp` writes the strings in the UDF headers. They can use 8-bit and 16-bit Unicode encodings, with the 8-bit variant effectively being the same thing as ISO-8859-1, which currently limits the generated labels in the ISO files to the characters supported by that encoding. Since metafiles are now officially supposed to use UTF-8, the only thing that should be needed is converting them to UTF-16BE (i.e. "16-bit OSTA Compressed Unicode" according to the language in the UDF specification) and storing them inside the headers. I just need to pull myself together and actually change the implementation, but I want to use the 16-bit variant only when strictly necessary in order not to change the encoding of the file names in the generated ISOs which might (or might not) break compatibility with some hardware players or whatnot.

**Comment by abakum** [comment]
ImgBurn is not open source, but can InfraRecorder code help?https://sourceforge.net/p/infrarecorder/code/ci/master/tree/

**Comment by abakum** [comment]
Maybe this will help?
https://www.mankier.com/8/udflabel
https://github.com/pali/udftools/tree/master/udflabel

**Comment by xavery** [comment]
The actual code is not the problem, it's the integration with the existing codebase that gives me nightmares. 😅

**Comment by abakum** [comment]
\8^)

**Comment by abakum** [comment]
> break compatibility with some hardware players or whatnot

I have 3 different hardware players. I can check
