### ISSUE TITLE
Some demuxed audio streams are out of sync (maximum delay add up to -0.5s)

### ISSUE THREAD

**Issue by lonecrane** [justdan96/tsMuxer#258]
Hi,

I've noticed obvious 'out of sync' issue for some audio streams demuxed from a BD. This is the 'WALL·E' UHD blu-ray produced by Disney, and the playlist 00800.mpls consists of 42 m2ts segments 56,61,57 and so one.  The audio streams out of sync include DTS-HD Master streams and Dolby ac3 streams, but with the exception of Dolby TrueHD. At the very beginning the V/A are in sync, but they lose sync gradually. At the very end, the audio streams behave a maximum delay of about -0.5s.
I have made some tests and it appears that txmuxer improprialy changes some audio frames close to the beginning of the segment #57 (but not the first frames). 
![fig 1](https://user-images.githubusercontent.com/36885830/77534074-fde43380-6ed2-11ea-8522-265d9bea2345.png)
- The top track is a DTS-HD Master stream demuxed with tsmuxer from the BD and then converted to flac:
`eac3to 00800.track_4353.dts 00800.track_4353.flac -mono`
- The second track is the DTS stream from 00061.m2ts, which is the second segment of the film.
`eac3to BDMV\STREAM\00061.m2ts 3: 1_61_3.dts`
`eac3to 1_61_3.dts 1_61_3.flac -mono`
- The third track is the the DTS stream from 00057.m2ts, which is the third segment of the film.
`eac3to BDMV\STREAM\00057.m2ts 3: 2_57_3.dts`
`eac3to 2_57_3.dts 2_57_3.flac -mono`

I've aligned segments 61 and 57 so that the audio frames overlap. We can find that tsmuxer has correctly concatenate the two segments at the time about 0:1:04.100. However, at the time mark #1 (0:1:04.783) the top track begins to be different from the third track:
![fig 2](https://user-images.githubusercontent.com/36885830/77535500-a7c4bf80-6ed5-11ea-93d5-7f4c26eecc52.png)
But in the next, if we align the time mark #2 of first track with the time mark #3 of the third track, the subsequent waveforms seem identical again. The duration from time mark #1 to #2 for the first track is only 6ms, but the actual duration from time mark #1 to #3 for the third track is 17ms, thus a time delay of -11ms is introduced here.
The timeshift will be accumulated by the subseqent segments, so maybe that's the very reason that why the overall time delay reaches -0.5s.
I had found this issue for a long time, but I didn't have proper tools (here is audacity 2.3.3, a freeware) to demonstrate it until I find similar bug report in another forum.

**Comment by yannick-92** [comment]
Hello

Amazing !!
It is true, and it is indeed a very old problem!
In my case, I have the same problem when I Demux an E-AC3 audio track to extract the Core AC3.
And when I remux this same .AC3 track in TSmuxer, I have a slight audio desynchronization when I watch the movie.
I did not have the courage to prove it for lack of skills and software to make the comparisons ...

Thx you so much for your job, hoping that the developers will find the solution?

Maybe you should also post this problem on the forum?
It should interest some people I think ...;)

Cordially

Yannick

**Comment by jcdr428** [comment]
@lonecrane good work with Audacity. Frame rate for DTS HDMA is 93.750 fps, so a difference of 10.667 sec. is exactly one frame. Although between m2ts 61 and 57, the additional frame does not seem to be a repetition of the previous one.

**Comment by lonecrane** [comment]
@yannick-92 @jcdr428 Thanks. I have run some further tests. 
I guess that this issue is related to the 'overlapped frame' so I try to cancel the removing detected overlapped frame by set the condition to constant false:
`if (/*m_demuxMode && */ m_mplsOffset > m_halfFrameLen) `
=> 
`if (/*m_demuxMode && */ m_mplsOffset*0 > m_halfFrameLen`
in simplePacketizerReader.cpp), and results are shown below.
![fig 4](https://user-images.githubusercontent.com/36885830/77618020-7c42e300-6f70-11ea-8fb0-784715d3de61.png)
I have aligned these demuxed tracks at the very beginning of m2ts segment 57 (the 3rd segment of the BD). By checking the delay at the very end of these tracks, it shows that the introduced delay of 11 ms for the DTS stream has been eliminated. But it seems that the AC3 stream always keep sync with the original track of m2ts, so this modification seems make no difference for the AC3 steam.
To find out the reason why AC3 streams also show timeshift (much more than that of DTS stream), the situation at the end of previous m2ts segment 61 should be checked:
![fig 5](https://user-images.githubusercontent.com/36885830/77618698-be205900-6f71-11ea-8595-acecca7f8091.png)
It seems that the original version of tsmuxer cut 5ms from the 2nd segment for the AC3 stream when concatenating the 3rd segment, and the modification version shows this delay is much reduced however not eliminated.

**Comment by justdan96** [comment]
@lonecrane Thanks a lot for this detailed analysis!

**Comment by yannick-92** [comment]
Very interesting !

In my case, I will try to explain where I get this delay during a remux of a full bluray disc, and then, the "DIY" solution that I found to work around the problem ...:

1): On a .ISO (full bluray), I open the .M2TS file of the main movie with TsMuxer 2.6.12.
In my case, I need to Demux the E-AC3 track to extract the Core AC3 because my old amplifier does not decode the E-AC3 audio tracks.
Okay, so I demux the E-AC3 track by not forgetting to check "Downconvert E-AC3 to AC3", and I get my AC3 track (.ac3 file).
J'usqu'à tout tout bien, I will now remux my .AC3 track with the other tracks to generate my movie in .M2TS.
Ok it's done, I have my perfectly remuxed .M2ts file (I think ...).
I launch the movie (on my PS3), and after a few minutes, the sound is slightly desynchronized, I immediately notice it because the dialogs are no longer in sync with the lips of the actors ... :(

2): Now the solution that I found and which works in my case:
I start again, but this time, I first made a .MKV of the original .M2TS file of the full bluray with MKVToolNix.
Okay, so I get my .MKV which I now open with TSMuxer 2.16.12.
So I demux my EAC-3 track, I get my .AC3 file, but this time, I remux it with MKVToolnix and I remake a .MKV.
Finally, I open my .MKV with TSMuxer to Muxer my file in .M2TS (the PS3 does not support .MKV ...)
I start playing the movie, no more desynchro!
Well, this technique works, don't ask me why, I'm not technically competent enough to explain it, but it works ...;)

Thank you all

Yannick

**Comment by abakum** [comment]
When I combine a movie from parts cut without transcoding for recording on BD, I record the sound of each part in LPCM, join the BD, demux the sound from BD, pack it for example to AC3 and replace the LPCM sound track of  BD with the AC3 sound track. Otherwise, so that there is lip sync, it is necessary that each part consists of an integer number of GOP of video and "FPS" of audio. The smaller the "FPS" of the audio, the greater the result shift due to misalignment.

**Comment by jcdr428** [comment]
@lonecrane having analysed the files 56, 61 and 57:
- At the end of 00056, the last DTS audio frame has an advance of 7.76ms > half-frame, so the frame is discarded and a delay of -2.91ms is reported to the next track.
- At the end of 00061, the last DTS audio frame has an advance of 3.88 ms / cumulative advance of 3.88-2.91 = 0.97ms < half-frame, so the last frame must not be discarded.

What is strange is that tsMuxer does not report any discarded frame at all. I am investigating.
