### ISSUE TITLE
Issues with Qt and Open Source

### ISSUE THREAD

**Issue by justdan96** [justdan96/tsMuxer#293]
You may have read in the news that "the Qt Company is evaluating restricting new releases to paying customers for 12 months". This is generating significant discussion in the open source community, you can see an example on the KDE Mailing List below:

https://mail.kde.org/pipermail/kde-community/2020q2/006098.html

There is already some discussion of forking Qt (I should add there is already a fork that has been around for some time but I'm not sure how maintained it is): https://www.copperspice.com/

Personally I feel like Qt does everything we want it to but it does present some challenges, particularly for Mac and Linux. Static linking for those platforms would be my preference but you can't easily statically link Qt. Qt is also a very large framework, I would be open to us using something more lightweight but there would be a lot of work involved in any migration.

I think we should monitor the situation for the time being. I'm creating the issue to track it and also foster discussion.

**Comment by Selur** [comment]
I think the static build thing is a more general problem on Mac and Linux and I doubt it would be easier using boost or other frameworks.
Personally I wouldn't have a problem with the open source branch hanging ~12month behind the normal releases, since the main stuff I use qt for, which is mainly basic gui stuff is kind of stable and hasn't changed much the last 10 years.

**Comment by xavery** [comment]
I think the past almost 2 years have shown that not a lot has changed and Qt lives on. Some distros have adopted building Qt 5.15 with patches from the KDE tree instead of waiting for official updates. Meanwhile, projects have moved to Qt 6 without much fanfare. tsMuxer itself has been buildable with Qt 6 since c2de3db345aff0e75ba3ec6484fd2d0c8e5078a7, but we're currently sticking with Qt 5.6 due to WinXP compatibility. Dropping WinXP support would mean we could update to Qt 5.15 as it's the last version to support Win7.

In the meantime, CopperSpice has not surfaced as a reasonable replacement for Qt, or at least I'm not aware of any projects switching to it.

Taking all this into account, I think it's best to close this. If anyone disagrees, feel free to reopen.

**Comment by justdan96** [comment]
Agree with all those points, thanks @xavery
