### ISSUE TITLE
[bug] meta file not updated when moving tracks up or down

### ISSUE THREAD

**Issue by jcdr428** [justdan96/tsMuxer#360]
From https://forum.doom9.org/showthread.php?p=1925000#post1925000:
```
In the track list, if you select a track and move it up, or down, you'll notice that its position in the metafile list does not change.
It will only change if you select a different track. The metafile list should change as soon as you move, up or down, a selected
track. Many moons ago I did a mux and noticed afterward that the order I wanted was not the order in the output. It was then I
discovered that moving a track doesn't actually move the track. It would be nice if moving a track actually moved the track in
the metafile list.
```

@xavery it seems `disableUpdatesCnt--;` should be moved before `updateMetaLines();` in tsmuxerwindows.cpp
However I do not fully understand the necessity/results of this disableUpdatesCnt, so it would be nice if you can have a look at this issue.

**Comment by xavery** [comment]
> I do not fully understand the necessity/results of this disableUpdatesCnt

Me neither. I've avoided touching it until now to avoid breaking stuff, but it seems like it's inevitable now. :-)

**Comment by xavery** [comment]
I "fixed" it by moving the decrement like you suggested, which makes `updateMetaLines()` do what it says. The main point of using this variable seems to be limiting the number of recomputations of the metafile - because a lot of `changed` signals in the GUI are supposed to change the metafile, they (usually indirectly) end up calling `updateMetaLines()`.
However, completely removing all references to this variable led to even worse results, with the generated metafile being completely out of sync with the GUI, so perhaps there is another reason to it that I just didn't decipher.
Resolving #188 would result in a lot of the code being simplified, with the only thing triggering a recomputation of the metafile being the model, instead of individual UI components. However, implementing this is simply too much work for little gain to the end user.
