### ISSUE TITLE
Incorrect Codec ID and Codec configuration box values for Dolby Vision profile 8 mux

### ISSUE THREAD

**Issue by GREMeZ** [justdan96/tsMuxer#390]
Accordint to "Dolby Vision Streams Within the ISO Base Media File Format Version 2.1.2 specification" for DV p8, converted from UHD BR, values should be:
Codec configuration box : hvcC+dvvC
Codec ID : hev1

tsmuxer sets only Codec ID: 36 and skip mandatory "Codec configuration box"

**Comment by jcdr428** [comment]
@GREMeZ "Dolby Vision Streams Within the ISO Base Media File Format Version 2.1" specification is for ISO MP4 files.

Please have a look at "Dolby Vision Streams Within the Mpeg-2 Transport Stream Format  Version 1.2" specification for Mpeg-TS: the value of stream_type (= Codec ID) is 0x24 = 36 for HDR or SDR compliant BL, or 6 otherwise.

**Comment by GREMeZ** [comment]
Thanks for clarification
