### ISSUE TITLE
Can't open H.266 (VVC) TS file - track 0 was not recognized and ignored

### ISSUE THREAD

**Issue by AlbertOpen** [justdan96/tsMuxer#444]
Good day
File is TransportRecord11973-59130659.ts (94 MB) https://disk.yandex.ru/d/eQseiH5X73uZyQ
Tried with tsMuxer 2021-06-20-02-13-48 in Win7x64

**Comment by jcdr428** [comment]
Hi @AlbertOpen, the revision of UIT-T H.222.0 | ISO/CEI 13818-1:2019/DAmd 2 (Carriage of VVC in MPEG-2 Systems) is not public yet:
https://www.itu.int/rec/T-REC-H.222.0-202106-P
https://www.iso.org/standard/80754.html

Unless somebody can provide, we cannot work on inclusion of VVC in tsMuxer yet.

**Comment by ccho111** [comment]
13818-1 8th edition is now FDIS (Final Draft Int. Standard), waiting for voting and becoming public standard.
However, the access right of the document is limited to MPEG members.

https://www.mpegstandards.org/meetings/mpeg-134/

**Comment by justdan96** [comment]
When will that information be available publicly?

**Comment by jcdr428** [comment]
@justdan96 the ITU Recommendation might never get public as it is also an ISO standard. It is not really a priority as there is no player able to play VVC yet, let's wait and see how ffmpeg or mkvtoolnix will do this.

**Comment by justdan96** [comment]
@jcdr428 thanks, I'm happy for this to be on the back burner until it has wide adoption then.

**Comment by justdan96** [comment]
@jcdr428 what does #451 change about this issue?

**Comment by jcdr428** [comment]
@justdan96 #451 allows VVC tracks to be recognized by tsMuxer. However this is WIP as the output TS stream is still not compliant: up to now some elements such as the VVC stream_id were not public.

The good news is that the updated MPEG-TS standard was made public yesterday: https://www.itu.int/rec/T-REC-H.222.0-202106-I/en . This should allow to finalize compatibility of ts-Muxer with VVC. 

Note that the sample provided by @AlbertOpen is not recognized as VVC because this is an old sample far from being compliant with the VVC MPEG standard. However, any sample compliant with the VVC standard -e.g. produced with Fraunhofer [VVenC](https://github.com/fraunhoferhhi/vvenc)- should be recognized (or if not, should be reported by the community).

**Comment by jcdr428** [comment]
Vvc has been included in tsMuxer. Closing.
