### ISSUE TITLE
Subtitle font size in tsMuxer Nightly versions always get back to default font size "65". Why?

### ISSUE THREAD

**Issue by anhlinhp4** [justdan96/tsMuxer#482]
In tsMuxer old versions, when I set a new font size for subtitle in "Subtitles" tab, tsMuxer will remember that new font size (for example, I set from "Arial, size 65" to "Arial, size: 50", tsMuxer will remember "size: 50" for re-opening it afterrward).
But a tsMuxer Nightly version does not keep that function. It always keeps back its default subtitle font "size 65" and I have to set my style of subtitle font size again and again whenever I opent it!
Why tsMuxer Nightly versions do not keep that convenient function like its old versions do?

**Comment by jcdr428** [comment]
@justdan96 I have traced the origin of the bug to commit #226 , however I can't see how this commit has created the bug / how to solve.

**Comment by jcdr428** [comment]
@xavery as you are the author of commit ce05c5d, it would be nice if you have time to look at this bug.

**Comment by xavery** [comment]
There's something really fishy going on with the code using `QSettings`. I don't have access to my Windows box at the moment, so this was just tested under Linux so far, however I'd suspect something similar going on under Windows. I could reproduce this with 9994ee5f444ef5f71bf21ce7220b66d55dc33633 as well, so I guess this has been an issue for quite a long time, at least under Linux.

The INI file created by the application contains doubled configuration entries if they belong to a group. This is a fresh INI generated by the application simply by starting, setting a different font size, family and colour, and exiting : 
```
[main]
blankPLNum=1900
hdmvPES=true
inputDir=/home/daniel
language=English
main\blankPLNum=1900
main\hdmvPES=true
main\inputDir=/home/daniel
main\language=English
main\outputDir=/home/daniel
main\outputToInputFolder=false
main\soundEnabled=true
main\useBlankPL=true
main\windowSize=@Size(1020 910)
outputDir=/home/daniel
outputToInputFolder=false
pip\corner=0
pip\h_offset=0
pip\size=0
pip\v_offset=0
soundEnabled=true
subtitles\color=4294967295
subtitles\fadeTime=0
subtitles\family=Arial
subtitles\fontBorder=5
subtitles\fontLineSpacing=1
subtitles\offset=24
subtitles\options=
subtitles\size=65
useBlankPL=true
windowSize=@Size(1020 711)

[pip]
corner=0
h_offset=0
size=0
v_offset=0

[subtitles]
color=4294901760
fadeTime=0
family=Calibri
fontBorder=5
fontLineSpacing=1
offset=24
options=
size=16
```

As you can see, the font settings under the `subtitles` group are actually specified twice in the resulting file : as `subtitles\xyz` under the `main` group, and as `xyz` under the `subtitles` group. To make matters worse, `subtitles\xyz` contain the old settings, while the settings under the `subtitles` group contains the new settings.
My guess is that, while reading, Qt disregards the `subtitles` group and uses the `subtitles\size` setting from `main` for some reason.

This is either a bug in Qt itself or our usage of `QSettings`. Unfortunately, I'd be leaning towards the latter, as the following program :
```cpp
#include <QSettings>

int main()
{
  QSettings x(QSettings::UserScope, "foobar", "foobar");
  x.beginGroup("main");
  x.setValue("xyz", "a");
  x.endGroup();

  x.beginGroup("foobar");
  x.setValue("abc", 42);
  x.endGroup();

  return 0;
}
```

produces the following INI file when compiled and run with Qt 5.6.3 : 
```
[foobar]
abc=42

[main]
xyz=a
```

**Comment by jcdr428** [comment]
@xavery nice to see you back on tsMuxer.

Your ini file looks like the `[main]` group has not been closed before calling the next group, therefore the other groups are nested. I can't see how this can happen in the code...

On Windows I don't have the same behavior. If I create a blank tsMuxerGUI.ini file, by modifying the font size I obtain:
```
[main]
soundEnabled=true
hdmvPES=true
inputDir=C:\\Users\\jcder\\
outputDir=C:/Users/jcder/
useBlankPL=false
blankPLNum=1900
outputToInputFolder=false
language=English
windowSize=@Size(1297 820)

[subtitles]
fontBorder=5
fontLineSpacing=1
offset=25
fadeTime=0
family=Calibri
size=10
color=4294967295
options=

[pip]
corner=0
h_offset=0
v_offset=0
size=0
```
So the size is correctly written in the [subtitles] group, however is not read (defaulted to 65) when opening tsMuxerGUI again -maybe because it is looking for

**Comment by xavery** [comment]
Okay, turns out this has nothing to do with how the INI files are written or how our code interacts with `QSettings`. While it's possible that there's still something wrong about it (after all, if everything was okay, we wouldn't have a weird INI file on our hands), it doesn't seem immediately related to this particular issue.

The issue is caused by `retranslateUi` being called after the language is set, possibly after loading settings. The implementation of `retranslateUi` brings back the default strings as set in the UI XML file, overwriting the ones loaded from the settings file : 

```cpp
        ___qtablewidgetitem13->setText(QApplication::translate("TsMuxerWindow", "Size:", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem14 = listViewFont->item(1, 1);
        ___qtablewidgetitem14->setText(QApplication::translate("TsMuxerWindow", "65", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem15 = listViewFont->item(2, 0);
        ___qtablewidgetitem15->setText(QApplication::translate("TsMuxerWindow", "Color:", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem16 = listViewFont->item(2, 1);
        ___qtablewidgetitem16->setText(QApplication::translate("TsMuxerWindow", "0xffffffff", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem17 = listViewFont->item(3, 0);
        ___qtablewidgetitem17->setText(QApplication::translate("TsMuxerWindow", "Charset:", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem18 = listViewFont->item(3, 1);
        ___qtablewidgetitem18->setText(QApplication::translate("TsMuxerWindow", "Default", Q_NULLPTR));
```

I removed the default strings from the UI file and they're now loaded in code, only if the fields are still empty after a `loadSettings` call. Things seem to be working fine now, and I also used this chance to remove the completely unused "Charset" option.

**Comment by xavery** [comment]
@anhlinhp4 This should be fixed in [the latest nightly](https://github.com/justdan96/tsMuxer/releases/tag/nightly-2021-11-02-02-05-05), please check and reopen if the bug still occurs.
