### ISSUE TITLE
language tags in m2ts file

### ISSUE THREAD

**Issue by toxa454** [justdan96/tsMuxer#506]
Sorry for my english. If I understand correctly, in the latest versions of the program language tags are located in 00000.clpi file in  CLIPINF and \BACKUP\CLIPINF folders. Are there options to make them in the m2ts file, as it was in the version 1.10.6? The plex media server, for example, does not have support for the BDMV structure, but it understands single m2ts, however, the voice languages are not displayed after the mux in this case.

**Comment by jcdr428** [comment]
@toxa454 current tsMuxer works the same way as 1.10.6: when you select m2ts (i.e. not Blu-ray or ISO), the language tags are written in the m2ts.

**Comment by toxa454** [comment]
@jcdr428 nope, I have a large personal collection of BDMV remuxes created by tsmuxer, now checked on 3 different films - in the latest night versions of tsmuxer, if I move m2ts from BDMV\STREAM\ or move (or delete) BDMV\BACKUP\CLIPINF\00000.clpi and BDMV\CLIPINF\00000.clpi, language tags in the Media Player Classic disappear. remuxes created in version 1.10.6 do not have this problem. I attach screenshots for the first situation.
https://ibb.co/tP5Lm61
https://ibb.co/DDMVJ9P

**Comment by jcdr428** [comment]
@toxa454 I thought you meant when muxing as m2ts or ts.
If you mux as Blu-ray or Iso, then the language descriptors are not part of the m2ts: this has been like this since version 1.12 / Sept-2013. The TS language decriptors are not authorized by the Blu-ray standards.

**Comment by xterran** [comment]
I confirm that there is a problem.
Currently, track languages ​​in remixes compiled via tmuxer 4K are stored in * .clpi files:
for languages ​​to be detected, these files must be present in at least one of the two folders:
or in \ BDMV \ CLIPINF
either to \ BDMV \ BACKUP \ CLIPINF
Then languages ​​are detected without problems:
https://ibb.co/SQd5tBZ

If all *.clpi files (or CLIPINF folders with them) are deleted, then the languages ​​disappear:
https://ibb.co/z8tVQgd

Accordingly, they disappear in the players, which is critical for Plex: for it you need to leave only 1 file 00000.m2ts, but in this case all languages ​​in Plex are "unknown" and they cannot be used normally.

This problem is not present on 1.10.6 - all languages ​​are stored in m2ts.

To be fair, I must say that the same problem is observed in original copies of BD4K discs, i.e. it is "laid down" by the standard, which, in my opinion, is clearly an erroneous decision: when deleting CLIPINF folders from the original BD4K, languages ​​from m2ts files disappear and Plex again has problems.

Please "flash" the languages ​​back into the m2ts file for 4K.

**Comment by jcdr428** [comment]
@xterran yes the "problem" exists also with all original Blu-ray structures, and as you point out, this is "laid down" by the standard: in a Blu-ray disk, the language is read from the clpi files, not from the m2ts files.
I don't use plex so I might have misunderstood the issue: if you need to leave only 00000.m2ts, why don't you mux directly to m2ts -which will then include the language descriptors ?

**Comment by xterran** [comment]
@jcdr428
"if you need to leave only 00000.m2ts, why don't you mux directly to m2ts"
I have different players, not just Plex. And the standard for all players has long been chosen - BDMV. Do you provide yourself with the scope of remixing several thousand ready-made BDMVs into m2ts, instead of simply taking out the finished m2ts with languages from the BDMV structure?
Please make a check mark (switch) in the settings, which is disabled by default, which activates the forced writing of languages to m2ts, as it was in 1.10.6. It is even possible with a warning that if activated, the Blu-Ray specification is violated (this is not a big deal).

**Comment by xterran** [comment]
@jcdr428, please make a separate (not for release) non-updatable "beta" version of tsmuxer 4K with languages added to m2ts in the BDMV structure. It is very much needed. I'm willing to pay. 
email: full-hd@yandex.ru

**Comment by jcdr428** [comment]
@xterran 
Windows 64: https://github.com/jcdr428/tsMuxer/suites/4759779782/artifacts/132127013
Linux: https://github.com/jcdr428/tsMuxer/suites/4759778546/artifacts/132126756

**Comment by xterran** [comment]
grate thanks!
