### ISSUE TITLE
Spanish language does not work at all

### ISSUE THREAD

**Issue by Oleekae** [justdan96/tsMuxer#669]
In the latest release it is said that the spanish button has been added, I guess it is not only the button but also the translation, well it doesn't work at all if so.

**Comment by Julvenzor** [comment]
Hi!
I am the one who has translated it into Spanish. Being a newbie, I've had some difficulties getting the translation into the code correctly. I have downloaded the latest automatically compiled version "nightly-2023-01-28-02-20-35" and the translation works. Only the view of embedded HTML fails. I will try to solve that.

Regards.

**Comment by Julvenzor** [comment]
Hi again!

As we can see here: https://github.com/justdan96/tsMuxer/actions/runs/4029707284/jobs/6927844897

The Linux build takes the "tsmuxergui_es.ts" file and processes it. Instead, the build process for Windows ignores it. I only see a difference between the Spanish translation and the others in terms of the number of translated/ignored strings. Is it due to an extension issue or something? Windows is very special with file names, but the ".ts" is specifically indicated and there are no spaces or strange characters.

In any case, I'm going to do some tests and if it works, I'll create another pull request.

Regards.

**Comment by Julvenzor** [comment]
Hi!

I have checked the Spanish translation, I have fixed an error that prevented the Spanish translation of the "about" tab from appearing and I have added the corresponding line to the Windows compilation script so that the "tsmuxergui_es.ts" file is compiled.

Regards.

**Comment by Julvenzor** [comment]
Changes here:

https://github.com/justdan96/tsMuxer/issues/669

**Comment by Julvenzor** [comment]
@Oleekae Can you confirm if the problem has been fixed? In my Windows virtual machine everything now works correctly.

Regards.

**Comment by Oleekae** [comment]
> @Oleekae Can you confirm if the problem has been fixed? In my Windows virtual machine everything now works correctly.
> 
> Regards.

First, thanks so much for your contribution and work in translating this great programme into spanish. Congratulations!

An yes, it's fully working now with build from 2023-01-30-02-16-12. Keep the good work, thanks so much again!!

Best regards!

**Comment by jcdr428** [comment]
@Julvenzor congrats for finalizing your first contribution. Hopefully the first of many, tsMuxer is a great project for learning c++ if you're also found of video coding.

**Comment by Julvenzor** [comment]
> @Julvenzor congrats for finalizing your first contribution. Hopefully the first of many, tsMuxer is a great project for learning c++ if you're also found of video coding.

Thank you very much, I'll try it. It is sad that life is so short to be able to learn everything we would like.

Regards.
