### ISSUE TITLE
Fehlermeldung - Can´t create temporary meta file ...

### ISSUE THREAD

**Issue by ronweb73** [justdan96/tsMuxer#93]
Hallo,
wenn ich eine Videodatei mit tsMuxeR 2.6.15 bearbeiten möchte, bekomme ich immer bei "Start muxing" die Fehlermeldung - Can´t create temporary meta file "C:\Users\Ronny_Weber\AppData\Local\Temp\tsMuxeR_VTS_01_1.meta". 
Als Betriebssystem verwende ich Windows7 Professional 64bit. 
Unter tsMuxeR 2.6.12 funktioniert alles ohne Fehlermeldung. Was mache ich falsch?
Vielen Dank für die Hilfe!

![tsmuxer 2 6 15](https://user-images.githubusercontent.com/59336029/71557626-dd7a1980-2a48-11ea-854c-50a90b31322e.jpg)

**Comment by xavery** [comment]
Es sieht so aus, als ob dein temporäres Verzeichnis unschriebbar wäre. Leider gab es keine Änderungen in der Funktion, die die Meta-Datei schreibt zwischen der ersten Version, die wir bekommen haben, und der aktuellen Version. 2.6.12 musste die Datei also irgendwo anders schreiben.

**Comment by justdan96** [comment]
@xavery you speak German as well? Multitalented! :smile: 

Google Translate, in case anyone else finds the same issue:

> 
> Hi there,
> 
> if I want to edit a video file with tsMuxeR 2.6.15, I always get the error message at "Start muxing" - Can´t create temporary meta file "C: \ Users \ Ronny_Weber \ AppData \ Local \ Temp \ tsMuxeR_VTS_01_1.meta".
> I use Windows7 Professional 64bit as the operating system.
> Under tsMuxeR 2.6.12 everything works without an error message. What am I doing wrong?
> Many thanks for the help!

> It looks like your temporary directory is not writable. Can you maybe try opening C: \ Users \ Ronny_Weber \ AppData \ Local \ Temp in Explorer and creating a file there?
> Unfortunately there were no changes in the function that the meta file writes between the first version we got and the current version. 2.6.12 had to write the file somewhere else.

**Comment by ronweb73** [comment]
Das temporäre Verzeichnis lässt sich beschreiben, daran liegt es nicht. Habe es auch auf einem anderen Rechner ausprobiert (Windows 7 Ultimate) - gleiches Problem.
Version 2.6.12 funktioniert und bei 2.6.15 kommt die Fehlermeldung ...

**Comment by jcdr428** [comment]
@ronweb73 just to make sure, your profile is C:\Users\Ronny_Weber (with the underscore) ?

@xavery I ask again because of the line 2390 in tsmuxerwindows.cpp `metaName = metaName.replace(' ', '_');` which is suspect and might have been added after 2.6.12.

**Comment by xavery** [comment]
@jcdr428 Great catch! The replace is done on the entire path instead of just the name of the file to be written. If the profile name is "Ronny Weber", then this space is going to be replaced and, in turn, lead to a directory that doesn't exist. However, the first version that we have (I'm going to have to create a tag for that commit) contains [the code in question](https://github.com/justdan96/tsMuxer/blob/71f0f89c93d608a84e90336613e17c8db1be1dfa/tsMuxerGUI/tsmuxerwindow.cpp#L2366) - it must've been added between the last 2.6.12 binary and the source release.

Anyhow, I reproduced this on Linux by setting `TMPDIR` to a location that contains spaces.
